/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (40000) [tconst]
      ,[titleType]
      ,[primaryTitle]
      ,[originalTitle]
      ,[isAdult]
      ,[startYear]
      ,[endYear]
      ,[runtimeMinutes]
      ,[genres]
  FROM [IMDB].[dbo].[TITLES]
